# Generated by Django 4.2.1 on 2023-05-26 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kundendatenbank', '0004_zeiteintrag'),
        ('arbeitsplanung', '0007_alter_zeiteintrag_mitarbeiter'),
        ('zeiterfassung', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zeiteintrag',
            name='kunde',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zeiterfassung_zeiteintraege', to='kundendatenbank.kunden'),
        ),
        migrations.AlterField(
            model_name='zeiteintrag',
            name='mitarbeiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zeiteintraege', to='arbeitsplanung.mitarbeiter'),
        ),
    ]
