# Generated by Django 4.2.1 on 2023-05-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeiterfassung', '0002_alter_zeiteintrag_kunde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zeiteintrag',
            name='stunden',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
