# Generated by Django 4.2.1 on 2023-05-26 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zeiterfassung', '0003_zeiteintrag_stunden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zeiteintrag',
            name='stunden',
        ),
    ]
