# Generated by Django 4.2.1 on 2023-05-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kunde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=200)),
                ('telefonnummer', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
