# Generated by Django 4.2.1 on 2023-05-26 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kundendatenbank', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kunde',
            new_name='Kunden',
        ),
    ]
