# Generated by Django 4.2.1 on 2023-05-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kundendatenbank', '0002_rename_kunde_kunden'),
    ]

    operations = [
        migrations.AddField(
            model_name='kunden',
            name='stundenansatz',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
