# Generated by Django 4.2.1 on 2023-05-26 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitsplanung', '0007_alter_zeiteintrag_mitarbeiter'),
        ('kundendatenbank', '0003_kunden_stundenansatz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zeiteintrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startzeit', models.DateTimeField()),
                ('endzeit', models.DateTimeField()),
                ('kunde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zeiteintraege', to='kundendatenbank.kunden')),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kundendatenbank_zeiteintraege', to='arbeitsplanung.mitarbeiter')),
            ],
        ),
    ]
