# Generated by Django 4.2.1 on 2023-05-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kundendatenbank', '0004_zeiteintrag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zeiteintrag',
            name='mitarbeiter',
        ),
        migrations.AddField(
            model_name='zeiteintrag',
            name='mitarbeiter_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
