# Generated by Django 4.2.1 on 2023-05-27 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kundendatenbank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arbeitsplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datum', models.DateField()),
                ('end_datum', models.DateField()),
                ('kunde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kundendatenbank.kunden')),
            ],
        ),
        migrations.CreateModel(
            name='Mitarbeiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginn_arbeitsverhaeltnis', models.DateField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='mitarbeiter_fotos/')),
                ('telefonnummer', models.CharField(max_length=15)),
                ('stundenlohn', models.DecimalField(decimal_places=2, max_digits=5)),
                ('verfuegbarkeit', models.CharField(choices=[('frei', 'Frei'), ('on work', 'On Work'), ('ferien', 'Ferien'), ('krank', 'Krank')], default='frei', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zeiteintrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbeitsplanung_zeiteintraege', to='arbeitsplanung.mitarbeiter')),
            ],
        ),
        migrations.CreateModel(
            name='Schicht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginn', models.TimeField()),
                ('ende', models.TimeField()),
                ('arbeitsplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arbeitsplanung.arbeitsplan')),
            ],
        ),
        migrations.AddField(
            model_name='arbeitsplan',
            name='mitarbeiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arbeitsplanung.mitarbeiter'),
        ),
    ]
