# Generated by Django 4.2.1 on 2023-05-26 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbeitsplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Mitarbeiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('beginn_arbeitsverhaeltnis', models.DateField()),
                ('foto', models.ImageField(upload_to='mitarbeiter_fotos/')),
            ],
        ),
        migrations.CreateModel(
            name='Schicht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginn', models.TimeField()),
                ('ende', models.TimeField()),
                ('arbeitsplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arbeitsplanung.arbeitsplan')),
            ],
        ),
        migrations.AddField(
            model_name='arbeitsplan',
            name='mitarbeiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arbeitsplanung.mitarbeiter'),
        ),
    ]
