# Generated by Django 4.2.1 on 2023-05-26 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitsplanung', '0001_initial'),
    ]

    operations = [
    ]
