# Generated by Django 4.2.1 on 2023-05-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitsplanung', '0002_auto_20230526_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitarbeiter',
            name='stundenlohn',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mitarbeiter',
            name='telefonnummer',
            field=models.CharField(default=20, max_length=15),
            preserve_default=False,
        ),
    ]
