# Generated by Django 4.2.1 on 2023-05-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitsplanung', '0003_mitarbeiter_stundenlohn_mitarbeiter_telefonnummer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitarbeiter',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='mitarbeiter_fotos/'),
        ),
    ]
