# Generated by Django 4.2.1 on 2023-05-26 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitsplanung', '0005_mitarbeiter_verfuegbarkeit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zeiteintrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zeiteintraege', to='arbeitsplanung.mitarbeiter')),
            ],
        ),
    ]
