# Generated by Django 4.2.1 on 2023-05-26 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitsplanung', '0006_zeiteintrag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zeiteintrag',
            name='mitarbeiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbeitsplanung_zeiteintraege', to='arbeitsplanung.mitarbeiter'),
        ),
    ]
