# Generated by Django 4.2.1 on 2023-05-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitsplanung', '0007_alter_zeiteintrag_mitarbeiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbeitsplan',
            name='schichten',
            field=models.ManyToManyField(related_name='arbeitsplaene', to='arbeitsplanung.schicht'),
        ),
    ]
