# Generated by Django 4.2.1 on 2023-05-26 14:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kundendatenbank', '0002_rename_kunde_kunden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rechnung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateField(auto_now_add=True)),
                ('gesamtsumme', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('bezahlt', models.BooleanField(default=False)),
                ('kunde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kundendatenbank.kunden')),
            ],
        ),
    ]
