# Generated by Django 4.2.1 on 2023-05-26 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitsplanung', '0006_zeiteintrag'),
        ('rechnungssystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rechnung',
            name='kunde',
        ),
        migrations.AddField(
            model_name='rechnung',
            name='mitarbeiter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='arbeitsplanung.mitarbeiter'),
            preserve_default=False,
        ),
    ]
