# Generated by Django 4.2.1 on 2023-05-26 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechnungssystem', '0003_remove_rechnung_mitarbeiter_rechnung_kunde_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rechnung',
            name='bezahlt',
        ),
        migrations.AlterField(
            model_name='rechnung',
            name='gesamtsumme',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
