# Generated by Django 4.2.1 on 2023-05-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechnungssystem', '0004_remove_rechnung_bezahlt_alter_rechnung_gesamtsumme'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechnung',
            name='monat',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
